### ISSUE TITLE
How to reduce the cost of shifting the QUEUE?

### ISSUE THREAD

**Issue by abeq** [StewEucen/fertile-forest-railsgem#1]
Where is the code in order to reduce the cost of shifting the QUEUE?
Would you please point to somewhere ?

**Comment by StewEucen** [comment]
Hi, nice to meet you.
You are first person who ask me for RailsGem of FF Model haha  

Please see method of ff_scoots_over.
It is for reducing cost of shifting the QUEUE.  

https://github.com/StewEucen/fertile-forest-railsgem/blob/v1.3.0/lib/fertile_forest/modules/reconstructers.rb

### My Idea for reducing cost to shift the QUEUE as:
1. When insert new node,  use QUEUE_DEFAULT_INTERVAL in fill_required_columns_to_append!().  
   > QUEUE_DEFAULT_INTERVAL is in:  
   https://github.com/StewEucen/fertile-forest-railsgem/blob/v1.3.0/lib/fertile_forest/saplings.rb  
   > fill_required_columns_to_append!(node) is in:  
   https://github.com/StewEucen/fertile-forest-railsgem/blob/v1.3.0/lib/fertile_forest/modules/calculators.rb
2. QUEUE_DEFAULT_INTERVAL  is 0x8000 = 32768. If there are enough space, child node QUEUE away 32768 from parent node QUEUE. Can insert new node between parent node and child node at half of 32768. At the time, not need to shift QUEUE for inserting new node.
3. 32768 can be divided in half 15 times. However, when 16 times to insert, there are no space for QUEUE. Just the time, method of scootsOver will work.
